calibration:
  laser_to_base_link:
    translation:
      x: 0.0
      y: 0.0
      z: 0.09
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
  imu_to_base_link:
    translation:
      x: 0.0
      y: 0.0
      z: 0.02
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
  camera_to_base_link:
    translation:
      x: 0.15
      y: 0.0
      z: 0.02
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0